### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by OlehRb**

### CODE REVIEW

**Comment by OlehRb** [comment]
Hi, @JiHong88 , firstly, thanks for an amazing open-sourced text editor
Our team is going to use it in some of our internal projects and we need it to be translated to Swedish
I know there is a possibility to provide custom translations for each particular application, but we thought it would be much more convincing to add a new locale directly to SunEditor

Would you, please, consider merging those translations?

**Comment by JiHong88** [comment]
Hi @OlehRb 
Thank you for your contribution!!
I'll notify you after update the version.

**Comment by OlehRb** [comment]
Hi @JiHong88 
Sorry to bother you, but is there any news, regarding when those changes are planned to be released?

**Comment by JiHong88** [comment]
@OlehRb It will be update today.

**Comment by JiHong88** [comment]
@OlehRb The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
Thank you.

**Comment by OlehRb** [comment]
@JiHong88 , super, thanks

**Pull request merged**
