### PR TITLE
Danish translations

### PR DESCRIPTION
**Pull request by davidkonrad**
Hope I have done it all correct. There is only two file changes: A lang/da.js and a change to lang/index.js. The translations does not seem to take effect on table and links, but I think this is a naming issue that will be corrected eventually.

### CODE REVIEW

**Comment by JiHong88** [comment]
Hi @davidkonrad :)

Thanks a lot!

Can you modify lang/da.js more?

Words related to tables have been added.

```javascript
...
minSize: 'Min size',
tableHeader: 'Table header',
mergeCells: 'Merge cells',
splitCells: 'Split Cells',
HorizontalSplit: 'Horizontal split',
VerticalSplit: 'Vertical split'
```

**Comment by davidkonrad** [comment]
Yes, I'll do that instantly. Hang on. FYI: Translations regarding tables
and hr-rules does not seem to take effect. Have not investigated further
(or checked with latest version) just a heads up

regards,
david

**Comment by davidkonrad** [comment]
Done. The additions seem to be included in the PR, so no further action
needed (from me), I guess. Have just updated and pushed to the repo.
Sorry, but I am not skilled to do this :) The only PR I have done before
was to Bootstrap Typeahead 5 years ago :)

regards,
david

**Comment by JiHong88** [comment]
Ok, That's enough about that : )

Thank you so much for your translation.

**Pull request merged**
