### PR TITLE
Base Theming for Sun Editor

### PR DESCRIPTION
**Pull request by booellean**
In response to issue #978, I have created a file called "_variables.css" that define all colors, font families, and data images involved in the styling of the editor. The editor supports light mode and dark mode out of the box. Custom themes and overrides can be added by the user.

I apologize for some of the style changes, my editor lints files when saving, and some changes are simply stylistic.

### CODE REVIEW

**Comment by reyx** [comment]
It generated a invalid value on suneditor.min.css 1881

1881 │   background-color: rgb(rgb(var(--se-grey-accent-13)))

**Comment by booellean** [comment]
> Thanks for the PR. It generated a invalid value on suneditor.min.css 1881
> 
> ```
> 1881 │   background-color: rgb(rgb(var(--se-grey-accent-13)))
> ```

I will look into it. Is this error outputted during the webpack build?

**Comment by booellean** [comment]
Thank you for your patience. The false value is now fixed.

**Comment by Md-Anamul-Haque** [comment]
--se-background-color-editable 
this css var is not found

**Comment by booellean** [comment]
> --se-background-color-editable this css var is not found

Thank you, this error is now resolved.

If there are still errors after this - I am doing these updates inside a docker container, so my configuration is a little different. I tried to set up a custom environment to be able to run the Karma tests to catch small issues like these, but I keep getting errors that I believe are inconsequential to my setup, such as "Uncaught SyntaxError: Cannot use import statement outside a module". What environment are you running the tests in so I can avoid these small hiccups?

**Comment by booellean** [comment]
Is there any other updates I need to work on for this branch?

**Comment by JiHong88** [comment]
@booellean Sorry for the late reply.
It's such a good PR, but I was thinking about how to do it.
"SunEditor" aims to support IE11 without dependencies and polyfills.
Considering compatibility with the previous version, it would be better to create one more css file with css variable applied.

**Pull request closed without merging**
