### PR TITLE
Improve embed video to gives a proper iframe

### PR DESCRIPTION
**Pull request by sudwebdesign**
Share embed code ok : archive.org, rumble, facebook, dailymotion (without first DIV)
And probably other...

After reading, understanding the algorithm and some successful tests with this regular expression...
The idea: youtube addresses are always detected because previously transformed with a /embed/ and additionally it avoids transforming many other platforms into video tag

.html, /e/ it's for certain platform and .php it's for facebook

### CODE REVIEW

**Comment by sudwebdesign** [comment]
So the below integration code from [peertube](https://joinpeertube.org) platform gives a proper iframe
```
<iframe title="Toile de confiance animée #4" src="https://tube.p2p.legal/videos/embed/af01fa25-e919-4a48-b777-68f9a835b8c6" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups" width="560" height="315" frameborder="0"></iframe>

```
[Archive.org](https://archive.org)
```
<iframe src="https://archive.org/embed/CC_1914_08_31_TheGoodforNothing" width="640" height="480" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
```
Facebook direct link : https://www.facebook.com/watch/?v=716493996428856 share with unpredictable url
```
<iframe src="https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Folympiquelyonnais%2Fvideos%2F716493996428856%2F&show_text=false&width=380&t=0" width="380" height="476" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
```

**Comment by JiHong88** [comment]
Thank you for your contribution!
I'll notify you after version update.

**Comment by admir4l** [comment]
Hi
I am trying to let my users embed a video from another website into my website using SunEditor and a quick search led me to this PR.

I check the code and there is a procedure that removes the iframe tag from the input and tries to use the URL as a video file and this is a problem in most cases where embedded iframes have their own players.

I checked the PR and it seems after this PR user can create an iframe in case of entering an URL that contains some special words. Is there any checking that prevents a user from showing an iframe that may have nonvideo contents using this option? if not whats the point of removing the iframe and generating it again in some special and limited cases?

I understand this PR improvement as it can convert URLs to iframe and create better compatibility. but I can not understand why you are removing the iframe tag from user input while most of the platforms generate an iframe tag when a user tries to share a video.

**Comment by JiHong88** [comment]
@admir4l 
Maybe I don't understand the question straight
This is to create only video "url" like "youtebe" with "iframe" tag.
For example, a video uploaded by a user to the server is created with a "video" tag. 

Verification is not performed separately.
If there is an iframe that can have non-video content, it will be created with a "video" tag.

**Comment by admir4l** [comment]
@JiHong88 
I know this is going to embed video from some websites as an iframe and I am sure this is helpful. but a user can insert an iframe with non-video content after this PR as it only checks the URL for some keywords. 

for example, if I use "http://suneditor.com/iframe/index.html" as a video URL the result is an iframe with non-video content.

image

on the other hand, there are lots of websites that offer sharing a video as an iframe and we can not add keywords for all of them!
for example:

```html
<iframe width="480" height="360" src="https://sample.com/t/4070/inframe/?biosci" frameborder="0" scrolling="no" allowfullscreen style="overflow: hidden;"></iframe>
```

The thing I am saying is if we allow users to insert an iframe just based on keywords on the URL it's also a good idea to do the same for codes like mentioned one to have even more capability to insert embedded videos. 

as a final point, this can add some security concerns too, and maybe enabling this behavior based on a whitelist (we can get this list as an option from the developer) can handle this concern a bit :)

**Pull request merged**
