### PR TITLE
Bug: correct conversion of quotes: single quote -> &apos;, double quote -> &quot;. Fixes gh-335

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by JiHong88** [comment]
Hi @rwaldron 
Thank you for your contribution!

**Comment by rwaldron** [comment]
@JiHong88 you're welcome!

**Comment by rwaldron** [comment]
@JiHong88 Thanks again for the quick merge. When do you think you'll have a chance to release SunEditor with this fix?

**Comment by JiHong88** [comment]
@rwaldron  I plan to resolve and release other issues by next Monday.

**Comment by JiHong88** [comment]
@rwaldron 
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
Thank you.

**Pull request merged**
