### PR TITLE
Fix : Toolbar sticky size, fullscreen to normal

### PR DESCRIPTION
**Pull request by sudwebdesign**
_offStickyToolbar: 
Size of toolbar when is sticky (from textarea), go fullscreen mode (ok) and click to return to normal mode (no fullscreen mode), the Toolbar is to large.

And to solve without this, when toolbar is sticky go on top page to unsticky toolbar ==  good width (same of textarea)

### CODE REVIEW

**Comment by sudwebdesign** [comment]
SE2 43 14 stycky-to-normal

**Comment by sudwebdesign** [comment]
With this fix ;-)
SE2 43 14 stycky-to-normal editorArea Fix

**Comment by JiHong88** [comment]
The size of the toolbar is not always the same as the size of the editor.
And there is no difference between the two screenshots.

**Comment by sudwebdesign** [comment]
> The size of the toolbar is not always the same as the size of the editor. And there is no difference between the two screenshots.

One first screenshot, look the second time call to fullscreen mode (when toolbar is sticky below the buttons in my case) and when return to normal mode, the toolbar size "width" as a same of fullscreen mode and set a good size when the toolbar unsticky (page go up), 1 line of icons change to 2 lines.

The second screenshot have this little fix, when is sticky, go to fullscreen (second call) & return to normal, the toolbar have directly good "width" (2 lines of icons), no need to go up to restore toolbar size.

Note: on both screenshots, the first call to go on fullscreen mode, the toolbar is not sicky and when return to normal mode the toolbar "width" change with good size ;) The problem arrives only when is sticky.

**Comment by sudwebdesign** [comment]
I would remove last \n but GH don't do it??? Sorry for that.

**Comment by JiHong88** [comment]
There is a problem with this method, so we will let you know after I fix it again.

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Pull request closed without merging**
