### PR TITLE
fix: deselect and prevent toolbar buttons enabling

### PR DESCRIPTION
**Pull request by SystemChanger**
Calling "readOnly(true)" didn't disable controllers (and other menus) resulting in incorrect buttons display state (blur off) after the selection is changed. 
"Enabled" dialogs (opened) and buttons (not blurred) resulted in ability to modify the contents when it should be prohibited.

UPD. Same for "disabled()"

### CODE REVIEW

**Comment by JiHong88** [comment]
Hi @SystemChanger 
The "more" button is intentionally enabled when "readOnly" or "disabled".
All buttons in "more layer" are disabled or abled depending on the type.

**Comment by SystemChanger** [comment]
@JiHong88
I can get it for "readOnly" but "disabled" affects the entire toolbar and "more layer" just takes up space.
Toolbar in "disabled" is blocked by this line: `context.tool.cover.style.display = 'block';`
So I think that for "disabled" we can have the following code:
```javascript
/** off menus */
core.submenuOff();
core.moreLayerOff();
core.containerOff();
core.controllersOff();
if (core.modalForm) core.plugins.dialog.close.call(core);
```
for readOnly:
```javascript
/** off menus */
core.controllersOff();
if (core.modalForm) core.plugins.dialog.close.call(core);
```
I have also removed the ` if (core.notice) core.notice.close.call(core);` line in my examples above.
"Controllers" and "modal form" should definitely be disabled cause they brings the major problems.

Also founded some issues with "readOnly" and will make card (issue) for them later.

**Comment by JiHong88** [comment]
@SystemChanger Thank for your contribution :)
I'll notify you after the version updated.

**Comment by JiHong88** [comment]
@SystemChanger The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Pull request merged**
