### PR TITLE
Mention Plugin

### PR DESCRIPTION
**Pull request by NickyTope**
Hi there,

I see there has been a couple of requests for a mention plugin in this repo.
I have implemented @mention in this pull request for your consideration.
I have tried to match the current patterns for other plugins as much as possible..
I could not translate the terms "Mention" and "Add Mention" into ckb lang file, do you have someone that can provide those?

Happy to discuss and change anything as required,

### CODE REVIEW

**Comment by JiHong88** [comment]
@NickyTope Thank you for your contribution!
You did a difficult task.
Thank you again.
I'll notify you after update the version.

**Comment by JiHong88** [comment]
Hi, @NickyTope 
I checked this PR.
I think this plugin is more suited to the modular format like github mentions.
I'll modify this plugin based on your code.
What is your think?

**Comment by NickyTope** [comment]
Hi @JiHong88 yes, I agree, it would be much better if this showed inline rather than using the standard dialog ui.

My aim with the PR was to use the standard utils you have provided with SunEditor but if you could expose a way to show the menu like they do here in github mentions that would be perfect.

Thank You

**Comment by gregoryforel** [comment]
Hi @NickyTope  and @JiHong88 ! Thanks for the plugin, I'm looking for an editor that supports mentions and hashtags and this could be the one. Do you have an example available on codesandbox or anything? Thanks in advance

**Comment by JiHong88** [comment]
Hi @gregoryforel This feature will be updated in version 3.0.0
I'll notify you after version update.

**Comment by bryant8888** [comment]
Hi @JiHong88 
I'm trying to figure out how to connect the mention plugin. Is he in working order at all?

**Pull request merged**
