### PR TITLE
fix: "toggleFullScreen" doesn't reset toolbar visibility now, fixed some grammatical mistakes

### PR DESCRIPTION
**Pull request by SystemChanger**
fix 1: "toggleFullScreen" doesn't reset toolbar visibility now.

fix 2: fixed some grammatical mistakes in the naming of methods and buttons.
"Disabled()" and "Enabled()" ones should be in the present-simple verb-form, not noun (or the past-simple form of verb), cause they are actions.
e.g. "Disabled()" -> "Disable()"

### CODE REVIEW

**Comment by JiHong88** [comment]
@SystemChanger Thanks for your work!
But renaming a method introduces backward compatibility issues.
The method name change is reflected in version 3.0.0.
Could you please resend only the bug fix part?

**Comment by SystemChanger** [comment]
@JiHong88 Yeah, I was thinking about backward compatibility too and was waiting for your reply about that.
Maybe we can have duplicates of these methods that reference the source?

**Comment by JiHong88** [comment]
@SystemChanger OK, It's possible!
It will be added to the v2.42.0.
Thank you :)

**Comment by JiHong88** [comment]
@SystemChanger The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Pull request merged**
